name: WordPress deploy

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
            node-version: 16.x
      - name: Get Diff
        uses: technote-space/get-diff-action@v5
        with:
          subdir: js
      - name: npm install
        if: steps.diff.outputs.diff-count > 0
        run: | 
          npm install
      - name: webpack build
        run: npm run build

      - name: SSH Key Settings
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Deploy
        run: ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no  ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'cd /usr/bedrock/web/app/themes/tomologo/ && git pull origin master && composer install && yarn'

      - name: Deploy bundle.js
        run: rsync -avzc -e  "ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT }} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" ./bundle.js  ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/usr/bedrock/web/app/themes/tomologo